services:
  message-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: message-service
    depends_on:
      - mongo
      - redis
    env_file:
      - .env
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"

  mongo:
    image: mongo:latest
    attach: false
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    attach: false
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

volumes:
  mongo-data:
